{"errors":["In the world's resolve_all_references step: In 'reference_outer_too_many_args': Reference error: In '@OUTER:1:2': invalid '@OUTER:1:2' found at position 0: Token '@OUTER:1:2' has multiple arguments (2) after the ':'. Can only have 1 argument or fewer."]}